"""adding followers relationship

Revision ID: 09afacb7440d
Revises: 563c42aa4ccf
Create Date: 2019-04-07 13:09:27.544667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09afacb7440d'
down_revision = '563c42aa4ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
