"""empty message

Revision ID: 563c42aa4ccf
Revises: e0d07cb9a552
Create Date: 2019-04-02 13:35:36.994957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563c42aa4ccf'
down_revision = 'e0d07cb9a552'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
